import type { QuizQuestion } from "@/types/quiz";

export const allTriggers = [
  "squats",
  "deadlifts",
  "long_sitting",
  "running",
  "bending",
  "lifting",
];

export const questions: QuizQuestion[] = [
  {
    id: 1,
    fieldName: "intro",
    type: "info",
    title: "Build Muscle, Protect Your Spine",
    description:
      "We combine professional coaching logic with spine-safe protocols to help you train hard without the fear of a flare-up. Let's customize your journey.",
    buttonText: "Start My Assessment",
  },
  {
    id: 1.5,
    fieldName: "workoutType",
    question: "Where do you plan to train?",
    type: "radio",
    options: ["Commercial Gym", "Home Gym / Limited Equipment"],
  },
  {
    id: 2,
    fieldName: "goal",
    question: "What is your primary objective?",
    type: "radio",
    options: [
      "Muscle Hypertrophy (Build mass safely with back/sciatica history)",
      "Structural Recovery (Reduce pain and restore movement capacity)",
    ],
  },
  {
    id: 3,
    fieldName: "baselineStats",
    question: "Standard Metrics",
    type: "multi_field",
    description: "These stats allow us to calibrate your volume and intensity.",
    optional: true,
    fields: [
      {
        id: 3.1,
        fieldName: "gender",
        label: "Gender",
        type: "radio",
        options: ["Male", "Female", "Other"],
        optional: true,
      },
      {
        id: 3.2,
        fieldName: "dateOfBirth",
        label: "Date of Birth",
        type: "date",
        optional: true,
      },
      {
        id: 3.3,
        fieldName: "height",
        label: "Height",
        type: "input",
        inputType: "number",
        placeholder: "Enter height",
        optional: true,
        unitOptions: ["cm", "ft"],
      },
      {
        id: 3.4,
        fieldName: "weight",
        label: "Weight",
        type: "input",
        inputType: "number",
        placeholder: "Enter weight",
        optional: true,
        unitOptions: ["kg", "lbs"],
      },
    ],
  },
  {
    id: 7,
    fieldName: "bodyType",
    question: "Which physique profile best matches yours?",
    type: "image_radio",
    options: [
      {
        value: "8-15",
        label: "Lean / Athletic",
        image: "/quiz/8-15.png",
        description: "Low body fat, visible definition.",
      },
      {
        value: "16-22",
        label: "Average / Fit",
        image: "/quiz/16-22.png",
        description: "Balanced composition, soft definition.",
      },
      {
        value: "23-30",
        label: "Overfat / Bulky",
        image: "/quiz/23-30.png",
        description: "Heavier midsection, less muscle clarity.",
      },
      {
        value: "30+",
        label: "High Body Fat",
        image: "/quiz/30-plus.png",
        description: "Significant fat storage, minimal definition.",
      },
    ],
    // OptionsFemale mapping remains the same as provided in your snippet
    optionsFemale: [
      { value: "18-24", label: "Lean / Athletic", image: "/quiz/female-18-24.png" },
      { value: "25-31", label: "Fit / Average", image: "/quiz/female-25-31.png" },
      { value: "32-38", label: "Overfat", image: "/quiz/female-32-38.png" },
      { value: "38+", label: "High Body Fat", image: "/quiz/female-38-plus.png" },
    ],
    showIf: {
      fieldName: "baselineStats",
      showOptionsBasedOn: true,
    },
    optional: true,
  },
  {
    id: 8,
    fieldName: "experience",
    question: "What is your resistance training experience?",
    type: "radio",
    options: [
      "Beginner (Learning the basics)",
      "Intermediate (1–3 years consistent training)",
      "Advanced (3+ years consistent training)",
    ],
  },
  {
    id: 9,
    fieldName: "trainingFrequency",
    question: "How many days per week can you commit?",
    type: "radio",
    options: ["2 Days", "3 Days", "4 Days", "5+ Days"],
  },
  {
    id: 10,
    fieldName: "painStatus",
    question: "What is your current spinal health status?",
    type: "radio",
    options: [
      "Healthy (I am pain-free, but cautious)",
      "Recovered (Past history of pain/injury)",
      "Active Symptoms (Currently experiencing discomfort)",
    ],
  },
  {
    id: 11,
    fieldName: "painLocation",
    question: "Identify your areas of sensitivity:",
    type: "checkbox",
    options: [
      "Lower Back (L4-L5/S1 area)",
      "Mid Back (Thoracic)",
      "Upper Back / Neck",
      "Sciatica (Radiating nerve pain)",
      "Glute / Hip / Leg",
      "Other",
    ],
    showIf: {
      fieldName: "painStatus",
      in: ["Recovered", "Active Symptoms"],
    },
  },
  {
    id: 12,
    fieldName: "painLevel",
    question: "Rate your current discomfort level (0–10):",
    type: "slider",
    min: 0,
    max: 10,
    showIf: { fieldName: "painStatus", equals: "Active Symptoms" },
  },
  {
    id: 13,
    fieldName: "painTriggers",
    question: "Which activities usually provoke symptoms?",
    type: "checkbox",
    options: [
      "Walking long distances",
      "Bending forward (Flexion)",
      "Lifting objects from the floor",
      "Sitting for long durations",
      "High-impact movement (Running/Jumping)",
      "Weighted Squats or Deadlifts",
      "Other functional movements",
    ],
    showIf: {
      fieldName: "painStatus",
      in: ["Recovered", "Active Symptoms"],
    },
  },
  {
    id: 14,
    fieldName: "canSquat",
    question: "How confident do you feel squatting with weights?",
    type: "radio",
    options: [
      "Confident (No pain issues)",
      "Cautious (Sometimes triggers pain)",
      "Avoidant (I strictly avoid them due to pain)",
      "Untested (I haven't tried recently)",
    ],
    showIf: {
      fieldName: "painStatus",
      in: ["Recovered", "Active Symptoms"],
    },
  },
  {
    id: 15,
    fieldName: "workoutDuration",
    question: "What is your ideal session length?",
    type: "radio",
    options: [
      "Express (20 min)",
      "Focused (30–45 min)",
      "Standard (45–60 min)",
      "Full Session (60+ min)",
    ],
  },
];